### ISSUE TITLE
Missing step for trusting your TLS certificates

### ISSUE THREAD

**Issue by ruidc** [customerio/customerio-python#102]
Certificates do not seem to be trusted on at least some Debian versions:

`python:3.10-slim-bookworm` (and bullseye)

`apt update && apt install -y ca-certificates`

```
request = SendEmailRequest(
    to="me@example.com",
    _from="me@example.com",
    subject="subj",
    message_data={
      "customer_first_name": "test",
    },
    body="sample body",
    identifiers={
      "email": "me@example.com",
    }
)
```

results in:
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /v1/send/email
Traceback (most recent call last):
  File "/Users/rui.dacostabeopen.com/.local/share/virtualenvs/test_customer_io-y84Bf5Xb/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/rui.dacostabeopen.com/.local/share/virtualenvs/test_customer_io-y84Bf5Xb/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/rui.dacostabeopen.com/.local/share/virtualenvs/test_customer_io-y84Bf5Xb/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/Users/rui.dacostabeopen.com/.local/share/virtualenvs/test_customer_io-y84Bf5Xb/lib/python3.10/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/Users/rui.dacostabeopen.com/.local/share/virtualenvs/test_customer_io-y84Bf5Xb/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/Users/rui.dacostabeopen.com/.local/share/virtualenvs/test_customer_io-y84Bf5Xb/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/rui.dacostabeopen.com/.pyenv/versions/3.10.13/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/rui.dacostabeopen.com/.pyenv/versions/3.10.13/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/rui.dacostabeopen.com/.pyenv/versions/3.10.13/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```

running 
`openssl s_client -showcerts -connect api-eu.customer.io:443`
confirms:
```
...
verify error:num=20:unable to get local issuer certificate
...
```

**Comment by ruidc** [comment]
It appears this was due to Clouflare VPN on my network environment and resigning of traffic.
