### ISSUE TITLE
unable to pip install?

### ISSUE THREAD

**Issue by jaddison** [customerio/customerio-python#28]
```
Collecting customerio==0.2 (from -r requirements.txt (line 2))
  Downloading customerio-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-to2j9f0e/customerio/setup.py", line 3, in <module>
        from customerio import get_version
      File "/tmp/pip-build-to2j9f0e/customerio/customerio/__init__.py", line 6, in <module>
        from requests import Session
    ImportError: No module named 'requests'
```

**Comment by hownowstephen** [comment]
Thanks for the report! you should be able to install the latest version `==0.2.2` properly now, see thread here https://github.com/customerio/customerio-python/pull/29 as to what was going wrong :)
