### ISSUE TITLE
Remote end drops connections periodically

### ISSUE THREAD

**Issue by georgy-scifind** [customerio/customerio-python#92]
Here is how we initialize the customerio client and call the API:
```python
    cio_client = CustomerIO(
        "site-id", "api-key"
    )
    cio_client.track(
        user_id,
        "event-name",
        **event_data,
    )
```

Periodically, on both our cloud environments (dev and prod), we see the following exceptions in the logs after trying to make a tracking API call:
```
  | 2023-02-24T08:28:59.027-05:00 | Traceback (most recent call last):
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
  | 2023-02-24T08:28:59.027-05:00 | httplib_response = self._make_request(
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
  | 2023-02-24T08:28:59.027-05:00 | six.raise_from(e, None)
  | 2023-02-24T08:28:59.027-05:00 | File "<string>", line 3, in raise_from
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
  | 2023-02-24T08:28:59.027-05:00 | httplib_response = conn.getresponse()
  | 2023-02-24T08:28:59.027-05:00 | File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
  | 2023-02-24T08:28:59.027-05:00 | response.begin()
  | 2023-02-24T08:28:59.027-05:00 | File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
  | 2023-02-24T08:28:59.027-05:00 | version, status, reason = self._read_status()
  | 2023-02-24T08:28:59.027-05:00 | File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
  | 2023-02-24T08:28:59.027-05:00 | raise RemoteDisconnected("Remote end closed connection without"
  | 2023-02-24T08:28:59.027-05:00 | http.client.RemoteDisconnected: Remote end closed connection without response
  | 2023-02-24T08:28:59.027-05:00 | During handling of the above exception, another exception occurred:
  | 2023-02-24T08:28:59.027-05:00 | Traceback (most recent call last):
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
  | 2023-02-24T08:28:59.027-05:00 | resp = conn.urlopen(
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
  | 2023-02-24T08:28:59.027-05:00 | retries = retries.increment(
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
  | 2023-02-24T08:28:59.027-05:00 | raise six.reraise(type(error), error, _stacktrace)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
  | 2023-02-24T08:28:59.027-05:00 | raise value.with_traceback(tb)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
  | 2023-02-24T08:28:59.027-05:00 | httplib_response = self._make_request(
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
  | 2023-02-24T08:28:59.027-05:00 | six.raise_from(e, None)
  | 2023-02-24T08:28:59.027-05:00 | File "<string>", line 3, in raise_from
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
  | 2023-02-24T08:28:59.027-05:00 | httplib_response = conn.getresponse()
  | 2023-02-24T08:28:59.027-05:00 | File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
  | 2023-02-24T08:28:59.027-05:00 | response.begin()
  | 2023-02-24T08:28:59.027-05:00 | File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
  | 2023-02-24T08:28:59.027-05:00 | version, status, reason = self._read_status()
  | 2023-02-24T08:28:59.027-05:00 | File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
  | 2023-02-24T08:28:59.027-05:00 | raise RemoteDisconnected("Remote end closed connection without"
  | 2023-02-24T08:28:59.027-05:00 | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
  | 2023-02-24T08:28:59.027-05:00 | During handling of the above exception, another exception occurred:
  | 2023-02-24T08:28:59.027-05:00 | Traceback (most recent call last):
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/customerio/client_base.py", line 37, in send_request
  | 2023-02-24T08:28:59.027-05:00 | response = self.http.request(
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
  | 2023-02-24T08:28:59.027-05:00 | resp = self.send(prep, **send_kwargs)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
  | 2023-02-24T08:28:59.027-05:00 | r = adapter.send(request, **kwargs)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
  | 2023-02-24T08:28:59.027-05:00 | raise ConnectionError(err, request=request)
  | 2023-02-24T08:28:59.027-05:00 | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
  | 2023-02-24T08:28:59.027-05:00 | During handling of the above exception, another exception occurred:
  | 2023-02-24T08:28:59.027-05:00 | Traceback (most recent call last):
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
  | 2023-02-24T08:28:59.027-05:00 | response = self.full_dispatch_request()
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
  | 2023-02-24T08:28:59.027-05:00 | rv = self.handle_user_exception(e)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
  | 2023-02-24T08:28:59.027-05:00 | rv = self.dispatch_request()
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
  | 2023-02-24T08:28:59.027-05:00 | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/app/webhooks/posts/http_handlers.py", line 233, in notify_followers
  | 2023-02-24T08:28:59.027-05:00 | self.send_customerio_new_post_event(customerio_user_ids, post_data)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/app/webhooks/posts/http_handlers.py", line 265, in send_customerio_new_post_event
  | 2023-02-24T08:28:59.027-05:00 | self.cio_client.track(
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/customerio/track.py", line 83, in track
  | 2023-02-24T08:28:59.027-05:00 | self.send_request('POST', url, post_data)
  | 2023-02-24T08:28:59.027-05:00 | File "/app/.venv/lib/python3.10/site-packages/customerio/client_base.py", line 52, in send_request
  | 2023-02-24T08:28:59.027-05:00 | raise CustomerIOException(message)
  | 2023-02-24T08:28:59.027-05:00 | customerio.client_base.CustomerIOException: Failed to receive valid response after 3 retries.
  | 2023-02-24T08:28:59.027-05:00 | Check system status at http://status.customer.io.
  | 2023-02-24T08:28:59.027-05:00 | Last caught exception -- <class 'requests.exceptions.ConnectionError'>: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
  | 2023-02-24T08:28:59.027-05:00 |  

<br class="Apple-interchange-newline">
```

We also see the following warning when nothing happens (no API calls to customerio being made, the client is just idle):
```
02-24-2023 08:22:21 AM WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /api/v1/customers/db230f25-8f45-4d0f-b0dc-8e17ae251d7e
```

Looking at the customerio client code seems like the problem might be with the connection pooling logic via session reusing. Could you please help us with this?

**Comment by mik3y** [comment]
I have seen this error occasionally, too. Essentially what I think is happening is Customer.io is closing the socket for some reason, before a complete response was set.

That would be a rare but by no means impossible situation. Some possibilities are: a kept-alive socket aged out & was closed (eg race condition); customer.io engineers were pushing out a release at "just the wrong time" & the socket got closed (dont actually know if this is how customer.io's releases or load balancer works); customer.io's load balancer decided to close the socket for reasons unknown.

Furthermore it looks like the `RemoteDisconnected` exception does _not_ trigger the retry logic (contra the error message); I found an attempt to fix that in urllib3, but the PR was abandoned: https://github.com/urllib3/urllib3/pull/1911

To fix locally, I suggest catching `RemoteDisconnected` and manually re-issuing the request. 

Possibly this could be handled more cleanly, if we could inject a `requests.Session` into the Customer.io client constructor; or if it was just handled within the library.

**Comment by georgy-scifind** [comment]
Thanks for your reply @mik3y. We fixed this error by disabling the connection pooling like this:
```python
    cio_client = CustomerIO(
        app.config["CUSTOMERIO_SITE_ID"],
        app.config["CUSTOMERIO_API_KEY"],
        use_connection_pooling=False,  # Connection pooling results in RemoteDisconnected errors.
    )
```
I hope it will help someone else.
